export enum NotificationType {
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_UNASSIGNED = 'TASK_UNASSIGNED',
    PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED',
    PROJECT_MEMBER_REMOVED = 'PROJECT_MEMBER_REMOVED',
    PROJECT_ROLE_CHANGED = 'PROJECT_ROLE_CHANGED',
    PROJECT_DELETED = 'PROJECT_DELETED',
}